---
# Automations
# this loads all automations,
# just add a new one in the folder and it will load on next restart
#
# Automations are stored by areas like bedroom, wardrobe, .... or system
#
# https://www.home-assistant.io/components/automation/
#

automation: !include_dir_list ../automations
