---
# the HTTP component configures access to the HA webfrontend
#
#

http:
  # base_url: !secret HA_BASE_URL

  # used due to the proxy setup I am using
  use_x_forwarded_for: true
  trusted_proxies: 
    - !secret PROXY_IP
    - 172.17.0.0/24


  # make it a bit more secure
  # ban after 5 wrong passwrods
  ip_ban_enabled: false
  login_attempts_threshold: 5
