---
# InfluxDB
# configuartion and
# defining what to log

influxdb:
  host: !secret INFLUX_HOST_IP
  username: !secret INFLUX_USER
  password: !secret INFLUX_PWD
  include:
    domains:
      - binary_sensor
      - sensor
      - switch
