---
# InfluxDB
# configuartion and
# defining what to log

influxdb:
  api_version: 2
  ssl: false
  host: !secret INFLUX_HOST_IP
  port: 8086
  token: !secret INFLUX_TOKEN
  organization: !secret INFLUX_ORG

  bucket: home_assistant
  #tags:
  #  source: HA
  tags_attributes:
    - friendly_name

  #measurement_attr: domain__device_class
  default_measurement: state
  include:
    domains:
      - binary_sensor
      - sensor
      - switch

  component_config_glob:
    sensor.*humi*:
      override_measurement: humidity
    sensor.*temp*:
      override_measurement: temperature
    sensor.*illumi*:
      override_measurement: illuminance
    sensor.*batt*:
      override_measurement: battery      