---
# Pi Hole integration
#
# https://www.home-assistant.io/integrations/pi_hole/
#

pi_hole:
  host: !secret PIHOLE_IP
  ssl: false
  verify_ssl: false
  api_key: 998ed4d621742d0c2d85ed84173db569afa194d4597686cae947324aa58ab4bb
  