---
# zigbee2mqtt networking package

zigbee2mqtt_networkmap:
# topic: your topic (optional, default zigbee2mqtt)

panel_iframe:
  networkmap:
    title: 'Zigbee Map'
    url: '/local/zigbee2mqtt_networkmap/map.html'
    icon: 'mdi:graphql'
