---
# custom component Composite Device Tracker
#
# https://github.com/pnbruckner/homeassistant-config/blob/master/docs/composite.md
#
# install:
#

platform: composite
name: Helen
entity_id:
  - device_tracker.helens_iphone8
  - device_tracker.nmap_helens_workphone
