---
# custom component Composite Device Tracker
#
# https://github.com/pnbruckner/homeassistant-config/blob/master/docs/composite.md
#
# install:
#
# yamllint disable-line rule:line-length
# wget https://raw.githubusercontent.com/pnbruckner/homeassistant-config/master/custom_components/device_tracker/composite.py
#

platform: composite
name: Roland
entity_id:
  - device_tracker.nmap_rolands_iphone
  - device_tracker.rolands_ios_app
  - device_traker.mobile_nokia6
