---
# Group defined as VIEW
#

RoomsLivingroom:
  name: Livingroom
  entities:
    - binary_sensor.livingroom_motion
    - media_player.living_room
    - media_player.living_room_speaker
    - media_player.living_room_tv
    - media_player.stereo
    - switch.plug_xmas_tree