---
# Group defined as VIEW
#

RoomsBedroom:
  name: Bedroom
  entities:
    # Office Light
    - switch.plug_l_switch
    # Rolands Light
    - switch.rolands_light
    # Helens Light
    - switch.helens_light
    # Ceiling Light
    - light.bedroom_light
    # Wardrobe Light
    - light.wardrobe_light
    - binary_sensor.motion_wardrobe
    - sensor.illumination_wardrobe
    # - group.RoomsEnsuite
