---
# Group defined as VIEW
#

Environment:
  entities:
    - sensor.humidity_hallway
    - sensor.temperature_hallway
    - sensor.temperature_balcony
    - sensor.humidity_balcony
    - sun.sun
