---
# Group defined as VIEW
#

RoomsHallway:
  name: Hallway
  entities:
    - binary_sensor.main_door_contact
    - sensor.device_xiaomi_gateway
    - switch.plug_hallway_switch
    - light.gateway_light_hallway
    - sensor.illumination_hallway
    - binary_sensor.hallway_motion
    - sensor.hallway_humidity
    - sensor.hallway_temperature
