---
# Group defined as VIEW
#

RoomsEnsuite:
  name: Ensuite
  entities:
    - light.ensuite_light
    - sensor.motion_ensuite_illuminance
    - binary_sensor.ensuite_motion
    - switch.ensuite_fan
    - sensor.ensuite_envirosensor_humidity
    - sensor.ensuite_envirosensor_temperature
    - sensor.humidity_delta
