---
# Group defined as VIEW
#

BedroomLights:
  name: Bedroom Lights
  entities:
    # Desk Light
    - switch.plug_l_switch
    # Rolands Light
    - switch.rolands_light
    # Helens Light
    - switch.helens_light
    # Ceiling Light
    - light.bedroom_light
    # Wardrobe Light
    - light.wardrobe_light
    # Ensuite Light
    - light.ensuite_light
