---
# Group defined as VIEW
#

UPS:
  name: UPS
  entities:
    - sensor.ups_battery
    - sensor.ups_input_voltage
    - sensor.ups_load
    - sensor.ups_output_voltage
    - sensor.ups_status
    - sensor.ups_time_left
    - sensor.ups_time_on_battery
    - sensor.ups_transfer_count
