---
# Group defined as VIEW
#

Nest:
  name: Nest Protect
  entities:
    - binary_sensor.hallway_nest_protect_online
    - sensor.hallway_nest_protect_battery_health
    - sensor.hallway_nest_protect_co_status
    - sensor.hallway_nest_protect_smoke_status
    - sensor.hallway_nest_protect_color_status
