---
# Group defined as VIEW
#

Devices_Mobiles:
  name: Mobiles
  entities:
    - sensor.device_nmap_helens_iphone
    - sensor.device_nmap_helens_workphone
    - sensor.device_nmap_rolands_iphone
    - sensor.device_nmap_rolands_nokia
    - sensor.rolands_work_phone_battery_state
    - sensor.rolands_work_phone_battery_level
