---
# Enables custom updated
#
custom_updater:
#  track:
#    - components
#    - python_scripts
#  component_urls:
#    - https://raw.githubusercontent.com/pnbruckner/homeassistant-config/master/custom_components.json
#  python_script_urls:
#    - https://raw.githubusercontent.com/pnbruckner/homeassistant-config/master/python_scripts.json
#  show_installable: true
