---
# Sets up Home Assistant customizations
#
# This fills in the customize section of the main config file

homeassistant:

  # customize individual entities
  customize: !include_dir_merge_named ../customizations/entities

  # custimize all entities in a domain
  customize_domain: !include_dir_merge_named ../customizations/domains

  # custimize entities based on a matching pattern
  customize_glob: !include_dir_merge_named ../customizations/globs
