---
# the HTTP component configures access to the HA webfrontend
#
#

http:
  base_url: !secret HA_BASE_URL
  
  # not required anymore  
  # api_password: !secret HA_PASSWORD

  # used due to the proxy setup I am using
  use_x_forwarded_for: True
  trusted_proxies: !secret PROXY_IP
  trusted_networks:
    - 127.0.0.1
    - 192.168.2.0/24
    
  # make it a bit more secure
  # ban after 5 wrong passwrods
  ip_ban_enabled: True
  login_attempts_threshold: 5
