---
# The yeelight component allows you to track and control yeelight light bulbs.
# This loads up my light configurations.
#
# https://www.home-assistant.io/components/yeelight/
#

discovery:
  ignore:
    - yeelight

yeelight:
  devices:
    !include_dir_merge_named ../components/yeelights
