---
# binary sensor WorkDay
#
# used mostly in the Homework Checks
#
# https://www.home-assistant.io/components/binary_sensor.workday/
#

platform: workday
name: Business Day
friendly_name: Business Day
country: AU
province: NSW
