## UNRAID VERSION ##

homeassistant:
  name: Home
  latitude: !secret HOME_LATITUDE
  longitude: !secret HOME_LONGITUDE
  unit_system: metric
  time_zone: Australia/Sydney
  elevation: 178

  customize: !include_dir_merge_named includes/customisations
  
  packages:
#    janetpack:      !include includes/packages/janet/janet.yaml
#    janetautopack:  !include includes/packages/janet/janet_automations.yaml
    
#    castpack:       !include includes/packages/Cast_Package.yaml
    devicepack:     !include includes/packages/Devices_Package.yaml   
    harmonypack:    !include includes/packages/Harmony_Package.yaml    
    xiaomipack:     !include includes/packages/Xiaomi_Package.yaml 
    #sonospack:      !include includes/packages/Sonos_Package.yaml 
 #   zanzitopack:    !include includes/packages/Zanzito_Package.yaml 
    piholepack:     !include includes/packages/PiHole_Package.yaml     
    apcupsdpack:    !include includes/packages/APCUPSd_Package.yaml     
    nestpack:       !include includes/packages/Nest_Package.yaml     
    loggingpack:    !include includes/packages/Logging_Package.yaml      
    ga_pack:        !include includes/packages/GoogleAssistant_Package.yaml
    battery_alert:  !include includes/packages/battery_alert.yaml
    enviro_pack:    !include includes/packages/Environment_Package.yaml
    efergy:         !include includes/packages/Efergy_Package.yaml
  
# Enables configuration UI
config:
  
# Enables the frontend
frontend:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:


logger:
  default: warn

#  logs:
#    homeassistant.custom_components.google_assistant: debug  
#    homeassistant.components.xiaomi_aqara: debug
#    homeassistant.components.sensor.xiaomi_aqara: debug
#    homeassistant.components.binary_sensor.xiaomi_aqara: debug
#    homeassistant.components.light.xiaomi_aqara: debug
#    homeassistant.components.switch.xiaomi_aqara: debug



ios:
  

       
 
http:
  base_url: !secret HA_BASE_URL
  api_password: !secret HA_PASSWORD
  use_x_forwarded_for: True
  ip_ban_enabled: True
  login_attempts_threshold: 5
  trusted_proxies: !secret PROXY_IP
  trusted_networks:
    - 127.0.0.1
    - 192.168.2.0/24
    
# Discover some devices automatically
discovery:
  ignore: 
  - yeelight


  
  
# Track the sun
sun:

# Text to speech
tts:
  platform: google

notify:
  - name: pushover
    platform: pushover
    api_key:  !secret PUSHOVER_API_KEY
    user_key: !secret PUSHOVER_USER_KEY 
    
  # using pushover for Janet! text notification  
  - name: janet
    platform: pushover
    api_key:  !secret PUSHOVER_API_KEY
    user_key: !secret PUSHOVER_USER_KEY    


mqtt:
  broker:    !secret MQTT_IP
  port:      !secret MQTT_PORT
  client_id: home-assistant
  keepalive: 60
  username:  !secret MQTT_USER
  password:  !secret MQTT_PWD
  discovery: true
  discovery_prefix: homeassistant  





    
#Includes  
group:          !include groups.yaml
sensor:         !include_dir_merge_list includes/sensors
zone:           !include includes/zones.yaml
device_tracker: !include includes/device_trackers.yaml
automation:     !include_dir_merge_list includes/automations


# testing stuff 




#panel_custom:
#  - name: floorplan
#    sidebar_title: Floorplan
#    sidebar_icon: mdi:home
#    url_path: floorplan
#    config: !include floorplan.yaml


    
    
# switches
switch:
  - platform: mqtt
    name: "Ensuite Fan"
    command_topic: "cmnd/sonoff_ensuite_fan/power"
    state_topic: "stat/sonoff_ensuite_fan/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true    
    
    
#person:
#  - firstname: Roland
#    lastname: Beck
#    gender: male
#    relationships:
#      - person: person.helen_beck
#        relation: WIFE
#    device_trackers:
#      - device_tracker.nmap_rolands_nexus
#
#  - firstname: Helen
#    lastname: Beck



#camera:
#  name: Roland
#  platform: generic
#  still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ states.device_tracker.zan_rolands_nexus.attributes.latitude }},{{ states.device_tracker.zan_rolands_nexus.attributes.longitude }}&zoom=13&size=500x500&maptype=roadmap&markers=color:blue%7Clabel:R%7C{{ states.device_tracker.zan_rolands_nexus.attributes.latitude }},{{ states.device_tracker.zan_rolands_nexus.attributes.longitude }}
#  limit_refetch_to_url_change: true