## UNRAID DOCKER VERSION ##

homeassistant:
  name: Home
  latitude: !secret HOME_LATITUDE
  longitude: !secret HOME_LONGITUDE
  unit_system: metric
  time_zone: Australia/Sydney
  elevation: 178

  customize: !include_dir_merge_named includes/customisations
  
  packages:
    gpsloggerpack:  !include includes/packages/GPSLogger_Package.yaml
    castpack:       !include includes/packages/Cast_Package.yaml
    devicepack:     !include includes/packages/Devices_Package.yaml   
#    harmonypack:    !include includes/packages/Harmony_Package.yaml    
    xiaomipack:     !include includes/packages/Xiaomi_Package.yaml 
    sonospack:      !include includes/packages/Sonos_Package.yaml 
    zanzitopack:  !include includes/packages/Zanzito_Package.yaml 
    
  
  
# Enables configuration UI
config:
  
# Enables the frontend
frontend:

 
http:
  #api_password: !secret HA_PASSWORD
  base_url: !secret HA_BASE_URL

  use_x_forwarded_for: True
  ip_ban_enabled: True
  login_attempts_threshold: 5
  trusted_networks:
    - 127.0.0.1
    - 192.168.2.0/24
    
# Discover some devices automatically
#discovery:


# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:


#logger:
#  default: warning
#  logs:
#    custom_components.xiaomi: debug
#    custom_components.sensor.xiaomi: debug
#    custom_components.switch.xiaomi: debug
#    custom_components.binary_sensor: debug
#    custom_components.light.xiaomi: debug


  
influxdb:
  host: !secret INFLUX_HOST_IP
  username: !secret INFLUX_USER
  password: !secret INFLUX_PWD
  
  
# Track the sun
sun:

# Text to speech
tts:
  platform: google

notify:
  - name: pushover
    platform: pushover
    api_key:  !secret PUSHOVER_API_KEY
    user_key: !secret PUSHOVER_USER_KEY 


mqtt:
  broker:    !secret MQTT_IP
  port:      !secret MQTT_PORT
  client_id: home-assistant
  keepalive: 60
  username:  !secret MQTT_USER
  password:  !secret MQTT_PWD






    
#Includes  
group:          !include groups.yaml
sensor:         !include_dir_merge_list includes/sensors
zone:           !include includes/zones.yaml
device_tracker: !include includes/device_trackers.yaml





# testing stuff 


camera:
  name: Roland
  platform: generic
  still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ states.device_tracker.rolands_nexus.attributes.latitude }},{{ states.device_tracker.rolands_nexus.attributes.longitude }}&zoom=13&size=500x500&maptype=roadmap&markers=color:blue%7Clabel:R%7C{{ states.device_tracker.rolands_nexus.attributes.latitude }},{{ states.device_tracker.rolands_nexus.attributes.longitude }}
  limit_refetch_to_url_change: true
