

views:
    # View tab title.
  - title: Example
    cards:
      - type: markdown
        title: Lovelace
        content: >
          Welcome to your **Lovelace UI**.
      - type: entity-filter
        entities:
          - device_tracker.rolands_work_phone
          - device_tracker.sonos_playbar
        state_filter:
          - 'home'
        card:
          type: glance
          title: People that are home          
      - type: picture
        image: /local/floorplanX.png         
        entities:
          - device_tracker.rolands_work_phone      
          

  - title: Floorplan
    id: floorplan
    cards:
      - type: picture-elements
        image: /local/floorplanX.png
        size: 200%
        elements:
          - type: state-icon
            entity: light.bedroom_light
            style:
              top: 78%
              left: 37%
          - type: state-icon
            entity: light.laundry_light
            style:
              top: 25%
              left: 59%
          - type: state-icon
            entity: light.bathroom_light
            style:
              top: 17%
              left: 43%   
          - type: state-icon
            entity: light.ensuite_light
            style:
              top: 55%
              left: 31%    
          - type: state-icon
            entity: light.wardrobe_light
            style:
              top: 55%
              left: 44%                 
          - type: state-icon
            entity: switch.plug_rolands_light
            style:
              top: 86%
              left: 48%                    
          - type: state-icon
            entity: switch.plug_158d0001288e14
            style:
              top: 72%
              left: 48%
          - type: state-icon
            entity: switch.plug_desk_light
            style:
              top: 88%
              left: 30%      
          - type: state-icon
            # motion laundry
            entity: binary_sensor.motion_laundry
            style:
              top: 18%
              left: 63%                   