---
# Entity configuration for Google Assistant.
#
# I use this to customize how the device shows up in Google Assistant.
#
# https://www.home-assistant.io/components/google_assistant/#entity_config
#

light.laundry_light:
  name: 'Laundry Light'
  room: Laundry
  expose: true
