---
# Device Sensor
# See readme for more details
#

device_sonos_playbar:
  entity_id: device_tracker.sonos_playbar
  value_template: '{% if is_state("device_tracker.sonos_playbar", "home") %}
                     Online
                   {% else %}
                     Offline
                   {% endif %}'
  icon_template: mdi:surround-sound
  friendly_name: Sonos Playbar
