---
# Device Sensor
# See readme for more details
#

device_obelix:
  entity_id: device_tracker.obelix
  value_template: '{% if is_state("device_tracker.obelix", "home") %} Online
                   {% else %} Offline {% endif %}'
  icon_template: '{% if is_state("device_tracker.obelix", "home") %} mdi:laptop
                  {% else %} mdi:laptop-off {% endif %}'
  friendly_name: Obelix
