---
# Device Sensor
# See readme for more details
#

device_xiaomi_gateway:
  entity_id: device_tracker.xiaomi_gateway
  value_template: '{% if is_state("device_tracker.xiaomi_gateway", "home") %}
                     Online
                   {% else %}
                     Offline
                   {% endif %}'
  icon_template: mdi:image-filter-tilt-shift
  friendly_name: Xiaomi Gateway
