---
# Device Sensor
# See readme for more details
#

device_google_home_felix:
  entity_id: device_tracker.felix_gh_mini
  value_template: '{% if is_state("device_tracker.felix_gh_mini", "home") %}
                     Online
                   {% else %}
                     Offline
                   {% endif %}'
  icon_template: mdi:home-circle
  friendly_name: Felix's Google Home
