---
# Automation running in the hallway
#
# simple automation to swtich the gateway light on on motion
# but only at night

alias: Hallway Lights by motion at night ON
initial_state: 'on'
condition:
  - condition: state
    entity_id: sun.sun
    state: 'below_horizon'
trigger:
  - platform: state
    entity_id: binary_sensor.motion_hallway
    to: 'on'
action:
  service: homeassistant.turn_on
  data:
    entity_id: light.gateway_light_hallway
    rgb_color: [25, 0, 150]
    brightness: 75
