# Automation running in the hallway
#
# simple automation to swtich the gateway light off after motion
#

alias: Hallway Lights by motion at night OFF
initial_state: 'on'
condition:
   - condition: state
     entity_id: sun.sun
     state: 'below_horizon'
trigger:
  - platform: state
    entity_id: binary_sensor.motion_hallway
    to: 'off'
    for:
      minutes: 0
      seconds: 30
action:
  service: homeassistant.turn_off
  data:
    entity_id: light.gateway_light_hallway