---
# Device Sensor
# See readme for more details
#

device_nmap_rolands_iphone:
  entity_id: device_tracker.nmap_rolands_iphone
  # yamllint disable-line rule:line-length
  value_template: '{% if is_state("device_tracker.nmap_rolands_iphone", "home"), "home") %}
                     Online
                   {% else %}
                     Offline
                   {% endif %}'
  icon_template: mdi:cellphone-iphone
  friendly_name: Roland's iPhone
