---
# Device Sensor
# See readme for more details
#

device_google_home_bedroom:
  entity_id: device_tracker.nmap_google_home_bedroom
  # yamllint disable-line rule:line-length
  value_template: '{% if is_state("device_tracker.nmap_google_home_bedroom", "home") %}
                     Online
                   {% else %}
                     Offline
                   {% endif %}'
  icon_template: mdi:home-circle
  friendly_name: Google Home Bedroom
