# --------------------------------------------------
# Automations running in the ensuite
# --------------------------------------------------

#  Ensuite Light by Motion
# =================================================
- alias: Ensuite Light by motion ON
  initial_state: 'on'
 # hidden: True
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_ensuite
      to: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: light.ensuite_light
    data_template: 
      brightness: >
        {% if   states.sensor.time_of_day.state == "night" %} 80
        {% else %} 255
        {% endif %}
      color_name: >
        {% if   states.sensor.time_of_day.state == "night"  %} blue
        {% else %} white
        {% endif %}
        
- alias: Ensuite Light by motion OFF
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_ensuite
      to: 'off'
      for:
        minutes: 0
        seconds: 30
    - platform: state
      entity_id: light.ensuite_light
      from: 'unavailable'
      to: 'on'
      for:
        minutes: 0
        seconds: 10
  action:
    service: homeassistant.turn_off
    data:
      entity_id: light.ensuite_light
      
#  Ensuite Fan by Motion
# =================================================
# switch on fan after motion for 1 minute.
# no fan at night! too noisy

- alias: Ensuite Fan by motion ON
  initial_state: 'on'
 # hidden: True
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_ensuite
      to: 'on'
      for:
        minutes: 1
        seconds: 0
  condition:
    condition: template
    value_template: '{{ states.sensor.time_of_day.state != "night" }}'          
  action:
    service: homeassistant.turn_on
    entity_id: switch.ensuite_fan
  
      

        

      
# If humidity in the ensuite is greater than in the hallway then keep running      
- alias: Ensuite Fan by Humidity
  initial_state: 'on'
  trigger:
    # when the fan switches off
    - platform: state
      entity_id: switch.ensuite_fan
      from: 'on'
      to: 'off'
      # to avoid the switch rattling    
      for:
        seconds: 10  
    # also check    
    # every hour at 5 past the hour  
    - platform: time
      minutes: 5
      seconds: 00      
  condition:
    - condition: template
      value_template: '{{ states.sensor.time_of_day.state != "night" }}'   
    - condition: numeric_state
      entity_id: sensor.humidity_delta
      above: 10
  action:
    service: homeassistant.turn_on
    entity_id: switch.ensuite_fan


# switch fan off after 5 minutes of running    
# if there is still motion it will start again
# if it is still humid it will start as well
- alias: Ensuite Fan OFF after 5:30 min
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: switch.ensuite_fan
      from: 'off'
      to: 'on'
      for:
        minutes: 5
        seconds: 30
  action:
    service: homeassistant.turn_off
    data:
      entity_id: switch.ensuite_fan    