# --------------------------------------------------
# Automations running in the laundry
# --------------------------------------------------


#  Laundry Light by Motion
# =================================================
- alias: Laundry Light by motion ON
  initial_state: 'on'
 # hidden: True
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_laundry
      to: 'on'
  action:
    service: homeassistant.turn_on
    data:
      entity_id: light.laundry_light
      #rgb_color: [25,0,150]
      brightness: 255

- alias: Laundry Light by motion OFF
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_laundry
      to: 'off'
      for:
        minutes: 3
  action:
    service: homeassistant.turn_off
    data:
      entity_id: light.laundry_light  