---
# custom component Composite Device Tracker
#
# https://github.com/pnbruckner/ha-composite-tracker
#

platform: composite
name: Helen
entity_id:
  - device_tracker.helens_iphone8
  - device_tracker.nmap_helens_workphone
