---
# Device Sensor
# See readme for more details
#

device_chromecast:
  entity_id: device_tracker.chromecast
  value_template: '{% if is_state("device_tracker.chromecast", "home") %}
                     Online
                   {% else %}
                     Offline
                   {% endif %}'
  icon_template: mdi:cast-sound
  friendly_name: Chromecast
