---
# Device Sensor
# See readme for more details
#

device_hp_tablet:
  entity_id: device_tracker.hp_tablet
  value_template: '{% if is_state("device_tracker.hp_tablet", "home") %}
                     Online
                   {% else %}
                     Offline
                   {% endif %}'
  icon_template: mdi:tablet
  friendly_name: Roland's Work Tablet
