---
# Device Sensor
# See readme for more details
#

device_iconia_tab:
  entity_id: device_tracker.iconia_tab
  value_template: '{% if is_state("device_tracker.iconia_tab", "home") %}
                     Online
                   {% else %}
                     Offline
                   {% endif %}'
  icon_template: mdi:tablet
  friendly_name: 'Iconia Tablet'
