---
# Device Sensor
# See readme for more details
#

device_purple_laptop:
  entity_id: device_tracker.purple_laptop
  value_template: '{% if is_state("device_tracker.purple_laptop", "home") %}
                     Online
                   {% else %}
                     Offline
                   {% endif %}'
  icon_template: '{% if is_state("device_tracker.purple_laptop", "home")%}
                    mdi:laptop
                  {% else %}
                    mdi:laptop-off
                  {% endif %}'
  friendly_name: 'Purple Laptop'
