---
# Device Sensor
# See readme for more details
#

device_nest_protect:
  entity_id: device_tracker.nmap_nest_protect
  value_template: '{% if is_state("device_tracker.nmap_nest_protect", "home") %}
                     Online
                   {% else %}
                     Offline
                   {% endif %}'
  icon_template: mdi:nest-protect
  friendly_name: Nest Protect
