---
# Device Sensor
# See readme for more details
#

device_nmap_helens_iphone:
  entity_id: device_tracker.nmap_helens_iphone
  value_template: '{%if is_state("device_tracker.nmap_helens_iphone", "home")%}
                     Online
                   {% else %}
                     Offline
                   {% endif %}'
  icon_template: mdi:cellphone-iphone
  friendly_name: Helen's iPhone
