- name: Work
  latitude:  !secret WORK_LATITUDE
  longitude: !secret WORK_LONGITUDE
  radius: 100
  icon: mdi:work  

- name: School
  latitude:  !secret SCHOOL_LATITUDE
  longitude: !secret SCHOOL_LONGITUDE
  radius: 100
  icon: mdi:work    