---
# block or release domains in PiHole
#

alias: Pihole Block Domains
initial_state: 'on'
trigger:
  platform: state
  entity_id: input_boolean.pihole_fun_blocked
  from: 'off'
  to: 'on'
action:
  service: shell_command.pihole_block_domains

