homeassistant:

# hide all device trackers by default!
#  customize_domain:
#    device_tracker:
#      hidden: true
# moved this to global customize file

      
sensor:
  - platform: template
    sensors: 
  

# MOBILE
      device_iconia_tab:
        entity_id: device_tracker.iconia_tab
        value_template: '{% if is_state("device_tracker.iconia_tab", "home") %}Online{% else %}Offline{% endif %}'
        icon_template: mdi:tablet
        friendly_name: 'Iconia Tablet' 

      device_galaxy_tab:
        entity_id: device_tracker.galaxy_tab
        value_template: '{% if is_state("device_tracker.galaxy_tab", "home") or is_state("device_tracker.galaxy_tab_ext", "home") %} Online {% else %} Offline {% endif %}'
        icon_template: mdi:tablet
        friendly_name: 'Galaxy Tablet'

# -- Helen        
      device_nmap_helens_workphone:
        entity_id: device_tracker.nmap_helens_workphone
        value_template: '{% if is_state("device_tracker.nmap_helens_workphone", "home") %}Online{% else %}Offline{% endif %}'
        icon_template: mdi:cellphone
        friendly_name: Helen's WorkPhone

      device_nmap_helens_iphone:
        entity_id: device_tracker.nmap_helens_iphone
        value_template: '{% if is_state("device_tracker.nmap_helens_iphone", "home") or is_state("device_tracker.nmap_helens_iphone_ext", "home") %} Online {% else %} Offline {% endif %}'
        icon_template: mdi:cellphone-iphone
        friendly_name: Helen's iPhone
        
# -- Roland
      device_nmap_rolands_iphone:
        entity_id: device_tracker.nmap_rolands_iphone
        value_template: '{% if is_state("device_tracker.nmap_rolands_iphone", "home") or is_state("device_tracker.nmap_rolands_iphone_ext", "home") %} Online {% else %} Offline {% endif %}'
        icon_template: mdi:cellphone-iphone
        friendly_name: Roland's iPhone
        
      device_nmap_rolands_nexus:
        entity_id: device_tracker.nmap_rolands_nexus
        value_template: '{% if is_state("device_tracker.nmap_rolands_nexus", "home") %}Online{% else %}Offline{% endif %}'
        icon_template: mdi:cellphone-android
        friendly_name: Roland's Nexus

# HOME AUTOMATION
      device_xiaomi_gateway:
        entity_id: device_tracker.xiaomi_gateway
        value_template: '{% if is_state("device_tracker.xiaomi_gateway", "home") %}Online{% else %}Offline{% endif %}'
        icon_template: mdi:image-filter-tilt-shift
        friendly_name: Xiaomi Gateway  

      device_xiaomi_gateway2:
        entity_id: device_tracker.xiaomi_gateway2
        value_template: '{% if is_state("device_tracker.xiaomi_gateway2", "home") %}Online{% else %}Offline{% endif %}'
        icon_template: mdi:image-filter-tilt-shift
        friendly_name: Xiaomi Gateway  

      device_google_home:
        entity_id: device_tracker.nmap_google_home
        value_template: '{% if is_state("device_tracker.nmap_google_home", "home") %}Online{% else %}Offline{% endif %}'
        icon_template: mdi:home-circle
        friendly_name: Google Home  

      device_google_home_bedroom:
        entity_id: device_tracker.nmap_google_home_bedroom
        value_template: '{% if is_state("device_tracker.nmap_google_home_bedroom", "home") %}Online{% else %}Offline{% endif %}'
        icon_template: mdi:home-circle
        friendly_name: Google Home Bedroom         

      device_felix_gh:
        entity_id: device_tracker.felix_gh_mini
        value_template: '{% if is_state("device_tracker.felix_gh_mini", "home") %}Online{% else %}Offline{% endif %}'
        icon_template: mdi:home-circle
        friendly_name: Felix's Google Home  

#      device_xenia_gh:
#        entity_id: device_tracker.felix_gh_mini
#        value_template: '{% if is_state("device_tracker.felix_gh_mini", "home") %}Online{% else %}Offline{% endif %}'
#        icon_template: mdi:home-circle
#        friendly_name: Xenia's Google Home           
#        
# SENSOR
      device_efergy_hub:
        entity_id: device_tracker.efergy_hub
        value_template: '{% if is_state("device_tracker.efergy_hub", "home") %}Online{% else %}Offline{% endif %}'
        icon_template: mdi:gauge
        friendly_name: Efergy Hub  
 
      device_nest_protect:
        entity_id: device_tracker.nmap_nest_protect
        value_template: '{% if is_state("device_tracker.nmap_nest_protect", "home") %}Online{% else %}Offline{% endif %}'
        icon_template: mdi:nest-protect
        friendly_name: Nest Protect         
        
          