
homeassistant:
  customize:
    sensor.efergy_591994:
      friendly_name: Energy Usage
    
    sensor.perdevice_usage:
      hidden: true
      
     
sensor:
  - platform: efergy
    app_token: !secret EFERGY_TOKEN
    utc_offset: 600
    monitored_variables:
#       - type: instant_readings
        - type: current_values