---
## UNRAID VERSION ##

# this home assistant config is a bit different.
# the file structure is inspired by frenck_nl
# https://github.com/frenck/home-assistant-config
#
# thanks for looking at it!
#

homeassistant:
  # some basic information on where we are ...
  name: Home
  latitude: !secret HOME_LATITUDE
  longitude: !secret HOME_LONGITUDE
  unit_system: metric
  time_zone: Australia/Sydney
  elevation: 178

  packages:
    !include_dir_named packages
hacs:
  token: !secret HACS_TOKEN
  
#  auth_providers:
#    - type: trusted_networks
#      trusted_networks:
#        - 127.0.0.1
#        - 192.168.2.0/24
#
