## UNRAID VERSION ##

# this unraid config is a bit different.
# the file structure is inspired by frenck_nl
# https://github.com/frenck/home-assistant-config
#
# thanks for looking at it!
#

homeassistant:

  # some basic information on where we are ...
  name: Home
  latitude: !secret HOME_LATITUDE
  longitude: !secret HOME_LONGITUDE
  unit_system: metric
  time_zone: Australia/Sydney
  elevation: 178

       
  
  packages:
  
  #all these will be imported by one statement once the rework is completed
  
  # packages: !include_dir_named components/packages
  
    homeassistant:  !include packages/homeassistant.yaml
    ios:            !include packages/ios.yaml
    logger:         !include packages/logger.yaml
    http:           !include packages/http.yaml  
    config:         !include packages/config.yaml  
    frontend:       !include packages/frontend.yaml  
    history:        !include packages/history.yaml  
    discovery:      !include packages/discovery.yaml  
    sun:            !include packages/sun.yaml  
    tts:            !include packages/tts.yaml  
    mqtt:           !include packages/mqtt.yaml     
    notify:         !include packages/notify.yaml     
    sensor:         !include packages/sensor.yaml  
    binary_sensor:  !include packages/binary_sensor.yaml    
    zone:           !include packages/zone.yaml        
    automation:     !include packages/automation.yaml
    device_tracker: !include packages/device_tracker.yaml
    
  # -------------------------------------------------------------  
  # old style packages setup
  
  # set some global environmental sensors (time of day, light of day,...)
  #  enviro_pack:    !include includes/packages/Environment_Package.yaml
  # composite devices
    compo_pack:     !include includes/packages/Composite_Package.yaml
  # customize devices 
    devicepack:     !include includes/packages/Devices_Package.yaml  
    
    harmonypack:    !include includes/packages/Harmony_Package.yaml    
    xiaomipack:     !include includes/packages/Xiaomi_Package.yaml 
    apcupsdpack:    !include includes/packages/APCUPSd_Package.yaml     
    nestpack:       !include includes/packages/Nest_Package.yaml     
  # logging to influx db
    loggingpack:    !include includes/packages/Logging_Package.yaml      
  # google assistant config and customisations
    ga_pack:        !include includes/packages/GoogleAssistant_Package.yaml
    battery_alert:  !include includes/packages/battery_alert.yaml
    efergy:         !include includes/packages/Efergy_Package.yaml
    customupdater:  !include includes/packages/CustomUpdater.yaml
    homeworkpack:   !include includes/packages/Homework_Package.yaml


    
## experimental packages mostly switched off
#    janetpack:      !include includes/packages/janet/janet.yaml
#    janetautopack:  !include includes/packages/janet/janet_automations.yaml
#    castpack:       !include includes/packages/Cast_Package.yaml
#    sonospack:      !include includes/packages/Sonos_Package.yaml 
#    zanzitopack:    !include includes/packages/Zanzito_Package.yaml 
#    piholepack:     !include includes/packages/PiHole_Package.yaml            # not using pihole on the new Google Wifi Router (yet)
#    lightdimmer:    !include includes/packages/LightDimmer.yaml               # couldn't make it work yet
#    ledpack: !include includes/packages/LED.yaml                              # it works, but LEDs are not installed at the moment
    


    
#Includes  
group:          !include groups.yaml
automation:     !include_dir_merge_list includes/automations


  
    
# switches
switch:
  - platform: mqtt
    name: "Ensuite Fan"
    command_topic: "cmnd/sonoff_ensuite_fan/power"
    state_topic: "stat/sonoff_ensuite_fan/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true    