---
## UNRAID VERSION ##

# this home assistant config is a bit different.
# the file structure is inspired by frenck_nl
# https://github.com/frenck/home-assistant-config
#
# thanks for looking at it!
#

homeassistant:


  packages:
    !include_dir_named integrations
