---
## UNRAID VERSION ##

# this home assistant config is a bit different.
# the file structure is inspired by frenck_nl
# https://github.com/frenck/home-assistant-config
#
# thanks for looking at it!
#

homeassistant:
  # some basic information on where we are ...
  name: Home
  latitude: !secret HOME_LATITUDE
  longitude: !secret HOME_LONGITUDE
  unit_system: metric
  time_zone: Australia/Sydney
  elevation: 178

  packages:

    !include_dir_named packages

    # homeassistant: !include packages/homeassistant.yaml
    # ios: !include packages/ios.yaml
    # logger: !include packages/logger.yaml
    # http: !include packages/http.yaml
    # config: !include packages/config.yaml
    # frontend: !include packages/frontend.yaml
    # history: !include packages/history.yaml
    # discovery: !include packages/discovery.yaml
    # sun: !include packages/sun.yaml
    # tts: !include packages/tts.yaml
    # mqtt: !include packages/mqtt.yaml
    # notify: !include packages/notify.yaml
    # sensor: !include packages/sensor.yaml
    # binary_sensor: !include packages/binary_sensor.yaml
    # zone: !include packages/zone.yaml
    # automation: !include packages/automation.yaml
    # device_tracker: !include packages/device_tracker.yaml
    # switch: !include packages/switch.yaml
    # apcupsd: !include packages/apcupsd.yaml
    # nest: !include packages/nest.yaml
    # influxdb: !include packages/influxdb.yaml
    # customupdater: !include packages/custom_updater.yaml
    # input_bool: !include packages/input_boolean.yaml
    # input_select: !include packages/input_select.yaml
    # device_sensor: !include packages/device_sensor.yaml
    # xiaomi: !include packages/xiaomi.yaml
    # light: !include packages/light.yaml
    # ga: !include packages/ga.yaml
    # battery_alert: !include packages/community_packages/battery_alert.yaml

# Includes
group: !include groups.yaml
