# --------------
# VIEWS
# --------------

Devices:
  view: yes
  entities:
    - group.devices_network
    - group.devices_computer
    - group.devices_mediaplayer
    - group.devices_gadgets
  
Rooms:
  view: yes
  name: Rooms
  entities:
    #- group.BedroomLights
    - group.RoomsBedroom
    - group.RoomsBathroom
    - group.RoomsLaundry
    - group.RoomsHallway
    - group.RoomsKitchen
    - group.RoomsEnsuite
    - group.RoomsLivingroom
    - group.RoomsFelix
    
Harmony:
  view: yes
  entities:
    - group.activity

        
Xioami_View:
  view: yes
  name: Xiaomi
  entities:
    - group.xiaomi1
    - group.xiaomi2

HomeworkTracker:
  view: yes
  name: HWT
  entities:
    - group.hwt
    - group.activity
    
Test_View:
  view: yes
  name: test
  entities:
    - group.occupancy
    
    
# --------------
# GROUPS
# --------------
hwt:
  view: no
  name: HWT Inputs
  entities:
    - binary_sensor.business_day
    - input_boolean.school_holiday
    - input_boolean.school_day
    - sensor.trello_count  
    - input_boolean.tv_restriction

Activity:
  view: no
  entities:
    - sensor.harmony_current_activity
    - input_select.harmony_control
    - remote.harmonyhub

Enviro:
  view: no
  entities:
    - sensor.time_of_day
    - sensor.light_of_day
    
   

Devices_Gadgets:
  name: Gadgets
  view: no
  entities:
    - sensor.device_efergy_hub
    - sensor.device_xiaomi_gateway
    - sensor.device_xiaomi_gateway2
    - sensor.device_iconia_tab 
    - sensor.device_nest_protect
    - sensor.device_google_home
    - sensor.device_google_home_bedroom
    
Devices_Phones:
  name: Mobiles
  view: no
  entities:  
    - sensor.device_nmap_helens_iphone
    - sensor.device_nmap_helens_workphone
    - sensor.device_nmap_rolands_iphone
    - sensor.rolands_work_phone_battery_state
    - sensor.rolands_work_phone_battery_level
    - sensor.device_nmap_rolands_nexus
    - sensor.zan_nexus_battery
    - sensor.device_galaxy_tab
    
Devices_Network:
  name: Network
  view: no
  entities:
    - sensor.device_modem_router
    #- sensor.device_repeater
    #- sensor.device_access_point
    - sensor.device_gate_pi  
    - sensor.device_hp_printer

Devices_Computer:
  name: Computer
  view: no
  entities:
    - binary_sensor.blue_laptop  
    - sensor.device_obelix
    - sensor.device_blue_laptop
    - sensor.device_purple_laptop
    - sensor.device_hp_tablet
    
Devices_MediaPlayer:
  name: Media Player
  view: no
  entities:
    - sensor.device_chromecast
    - sensor.device_audiocast
    - sensor.device_fetch
    - sensor.device_roku
    - sensor.device_sonos_playbar
    
Monitoring:
  view: no
  entities:
    - sensor.crashplan_status
    - binary_sensor.zan_nexus_status
    - sensor.zan_nexus_battery
#    - sensor.energy_usage
    - sensor.efergy_591994


Environment:
  view: no
  entities: 
    - sensor.humidity_hallway
    - sensor.temperature_hallway
    - sensor.hallway
    - sensor.balcony
    - sensor.laundry
        
Weather:
  view: no
  entities:
    - sensor.bom_sydney_air_temp_c
    - sensor.bom_sydney_weather
    - sensor.bom_sydney_wind_direction
    - sensor.bom_sydney_wind_speed_kt
    - sensor.bom_sydney_wind_speed_kmh    
    - sensor.dark_sky_icon
    - sensor.dark_sky_temperature
    - sun.sun
    - sensor.yr_symbol
    
   
Xiaomi1:
  name: Gateway 1
  view: no
  entities:
    - sensor.xiaomi_gateway
    - light.gateway_light_hallway
    - sensor.illumination_hallway
    - binary_sensor.motion_hallway

    - binary_sensor.door_appartment_door
    - sensor.front_door    
    - sensor.humidity_hallway
    - sensor.temperature_hallway    
    - sensor.humidity_balcony
    - sensor.temperature_balcony 
    - sensor.humidity_ensuite
    - sensor.temperature_ensuite
    - binary_sensor.motion_kitchen
    - binary_sensor.motion_livingroom
    - binary_sensor.motion_bathroom
    - binary_sensor.switch_button_f

Xiaomi2:
  name: Gateway 2
  view: no
  entities:
    - sensor.xiaomi_gateway2
    - light.gateway_light_gateway2
    - sensor.illumination_gateway2
    # Office Light
    - binary_sensor.switch_button_l
    - switch.plug_desk_light
    # Rolands Light
    - binary_sensor.switch_button_r
    - switch.plug_rolands_light
    # Helens Light    
    - binary_sensor.switch_button_h
    - switch.plug_helens_light
    # bedroom
    - binary_sensor.motion_wardrobe
    - light.bedroom_light
    - light.wardrobe_light

    
BedroomLights:
  name: Bedroom Lights
  view: no
  entities:
    # Office Light
    - switch.plug_desk_light
    # Rolands Light
    - switch.plug_rolands_light
    # Helens Light    
    - switch.plug_helens_light
    # Ceiling Light
    - light.bedroom_light
    # Wardrobe Light
    - light.wardrobe_light
    # Ensuite Light
    - light.ensuite_light


RoomsBathroom:
  name: Bathroom
  view: no
  entities:
    - light.bathroom_light
    - binary_sensor.motion_bathroom
    - sensor.illumination_bathroom

RoomsFelix:
  name: Felix's Room
  view: no
  entities:
    - light.felix_light    
    
RoomsBedroom:
  name: Bedroom
  view: no
  entities:
    # Office Light
    - switch.plug_desk_light
    # Rolands Light
    - switch.plug_rolands_light
    # Helens Light    
    - switch.plug_helens_light
    # Ceiling Light
    - light.bedroom_light
    # Wardrobe Light
    - light.wardrobe_light
    - binary_sensor.motion_wardrobe
    - sensor.illumination_wardrobe
    - group.RoomsEnsuite

RoomsEnsuite:
  name: Ensuite
  view: no
  entities:
    - light.ensuite_light
    - sensor.illumination_ensuite
    - binary_sensor.motion_ensuite
    - switch.ensuite_fan
    - sensor.humidity_ensuite
    - sensor.temperature_ensuite
    - sensor.humidity_delta
    
    
RoomsLaundry:
    name: Laundry
    view: no
    entities:
      - binary_sensor.water_leak_sensor_laundry
      - light.laundry_light
      - binary_sensor.motion_laundry
      - sensor.illumination_laundry    


RoomsKitchen:
  name: Kitchen
  view: no
  entities:
    - binary_sensor.motion_kitchen

RoomsHallway:
  name: Hallway
  view: no
  entities:
    - sensor.xiaomi_gateway
    - light.gateway_light_hallway
    - sensor.illumination_hallway
    - sensor.humidity_hallway
    - sensor.temperature_hallway
    
RoomsLivingroom:
  name: Livingroom
  view: no
  entities:
    - binary_sensor.motion_livingroom
    - switch.plug_xmas_tree
    
    
Nest:
  name: Nest Protect
  view: no
  entities:
    - binary_sensor.hallway_nest_protect_online
    - sensor.hallway_nest_protect_battery_health
    - sensor.hallway_nest_protect_co_status
    - sensor.hallway_nest_protect_smoke_status
    - sensor.hallway_nest_protect_color_status
    
UPS:
  name: UPS
  view: no
  entities: 
    - sensor.ups_battery
    - sensor.ups_input_voltage
    - sensor.ups_load
    - sensor.ups_output_voltage
    - sensor.ups_status
    - sensor.ups_time_left
    - sensor.ups_time_on_battery
    - sensor.ups_transfer_count        

GoogleWiFi:
  name: Google WiFi
  view: no
  entities:
    - sensor.onhub_packets_sent
    - sensor.onhub_bytes_sent
    - sensor.onhub_packetssec_sent
    - sensor.onhub_bytes_received
    - sensor.onhub_packetssec_received
    - sensor.onhub_kbytesec_sent
    - sensor.onhub_packets_received
    - sensor.onhub_kbytesec_received
    