---
# a fake secrets.yaml file for travis-ci
# this is used to pass the configuration check
# but obiously does not include any real information
#

HA_PASSWORD: XXXXXXX
HA_BASE_URL: XXXXXXX
PROXY_IP: 192.168.1.1

HOME_LATITUDE: -12.345678
HOME_LONGITUDE: 12.345678

WORK_LATITUDE: -12.345678
WORK_LONGITUDE: 12.345678

SCHOOL_LATITUDE: -12.345678
SCHOOL_LONGITUDE: 12.345678

HOST_IP: 192.168.1.1
PLEX_HOST_IP: 192.168.1.1
TOWER_IP: 192.168.1.1
GH_MASTERBEDROOM_IP: 192.168.1.1
GH_LIVINGROOM_IP: 192.168.1.1

INFLUX_HOST_IP: 192.168.1.1
INFLUX_USER: XXXXXXX
INFLUX_PWD: XXXXXXX

PUSHOVER_API_KEY: XXXXXXX
PUSHOVER_USER_KEY: XXXXXXX

DARKSKY_API_KEY: XXXXXXX

MQTT_IP: 192.168.1.1
MQTT_PORT: 1883
MQTT_USER: XXXXXXX
MQTT_PWD: XXXXXXX

HARMONY_USER: XXXXXXX@XXXXXXX
HARMONY_PWD: XXXXXXX
HARMONY_IP: 192.168.1.1

EFERGY_TOKEN: XXXXXXX

XIAOMI_KEY_1: xxxxxxxxxxxxxxxx
XIAOMI_MAC_1: xxxxxxxxxxxx

XIAOMI_KEY_2: yyyyyyyyyyyyyyyy
XIAOMI_MAC_2: yyyyyyyyyyyy

PIHOLE_IP: 192.168.1.1

NEST_CLIENT_ID: XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX
NEST_CLIENT_SECRET: XXXXXXX

GOOGLE_ASSISTANT_PROJECT_ID: XXXXXXX-XXXXXXX
GOOGLE_ASSISTANT_API_KEY: XXXXXXX-XXXXXXX
GOOGLE_ASSISTANT_CLIENT_ID: XXXXXXX
GOOGLE_ASSISTANT_TOKEN: XXXXXXX
GOOGLE_ASSISTANT_USER_ID: XXXXXXX

MARIADB: mysql://user:passowrd@192.168.1.1:3306/homeassistant?charset=utf8

HACS_TOKEN: 1234567890