---
# Lovelace Frontend Configuration

# this is the stub of the lovelace configuration
# all files are in their respective folders again

# views are called out individually to guarnatee order
  
views:
  - !include lovelace/views/home.yaml
  - !include lovelace/views/rooms.yaml
 # - !include lovelace/views/floorplan.yaml
  - !include lovelace/views/z2m.yaml
 #  - !include lovelace/views/battery.yaml
  - !include lovelace/views/stuff.yaml
 # - !include lovelace/views/zigbee2mqtt-networkmap.yaml