homeassistant:

# hide all device trackers by default!
  customize_domain:
    device_tracker:
      hidden: true
     
sensor:
  - platform: template
    sensors: 

# NETWORK
      device_modem_router:
        value_template: '{% if is_state("device_tracker.modem_router", "home") %}Online{% else %}Offline{% endif %}'
        icon_template: mdi:router-wireless
        friendly_name: Modem/Router  

      device_repeater:
        value_template: '{% if is_state("device_tracker.repeater", "home") %}Online{% else %}Offline{% endif %}'
        icon_template: mdi:access-point-network
        friendly_name: Repeater  
  
      device_gate_pi:
        value_template: '{% if is_state("device_tracker.raspberry_pi", "home") %}Online{% else %}Offline{% endif %}'
        icon_template: mdi:wall
        friendly_name: Gate Pi  

        
# MEDIA PLAYER
      device_fetch:
        value_template: '{% if is_state("device_tracker.fetch", "home") %}Online{% else %}Offline{% endif %}'
        icon_template: mdi:camcorder-box
        friendly_name: FetchTV Box

      device_sonos_playbar:
        value_template: '{% if is_state("device_tracker.sonos_playbar", "home") %}Online{% else %}Offline{% endif %}'
        icon_template: mdi:surround-sound
        friendly_name: Sonos Playbar  

      device_chromecast:
        value_template: '{% if is_state("device_tracker.chromecast", "home") %}Online{% else %}Offline{% endif %}'
        icon_template: mdi:cast
        friendly_name: Chromecast 
  
      device_roku:
        value_template: '{% if is_state("device_tracker.roku", "home") %}Online{% else %}Offline{% endif %}'
        icon_template: mdi:camcorder-box
        friendly_name: Roku

      device_audiocast:
        value_template: '{% if is_state("device_tracker.audiocast", "home") %}Online{% else %}Offline{% endif %}'
        icon_template: mdi:music-box-outline
        friendly_name: Audio Cast       
        

# LAPTOP / SERVER
      device_hp_tablet:
        value_template: '{% if is_state("device_tracker.hp_tablet", "home") %}Online{% else %}Offline{% endif %}'
        icon_template: mdi:tablet
        friendly_name: Roland's Work Tablet  

      device_obelix:
        value_template: '{% if is_state("device_tracker.obelix", "home") or is_state("device_tracker.obelix_ext", "home") %} Online {% else %} Offline {% endif %}'
        icon_template: '{% if is_state("device_tracker.obelix", "home") or is_state("device_tracker.obelix_ext", "home") %} mdi:laptop {% else %} mdi:laptop-off {% endif %}'
        friendly_name: Obelix

      device_blue_laptop:
        value_template: '{% if is_state("device_tracker.blue_laptop", "home") %}Online{% else %}Offline{% endif %}'
        icon_template: '{% if is_state("device_tracker.blue_laptop", "home") %}mdi:laptop{% else %}mdi:laptop-off{% endif %}'
        friendly_name: 'Blue Laptop'
 
      device_purple_laptop:
        value_template: '{% if is_state("device_tracker.purple_laptop", "home") %}Online{% else %}Offline{% endif %}'
        icon_template: '{% if is_state("device_tracker.purple_laptop", "home") %}mdi:laptop{% else %}mdi:laptop-off{% endif %}'
        friendly_name: 'Purple Laptop'
         
      device_hp_printer:
        value_template: '{% if is_state("device_tracker.hp_printer", "home") %}Online{% else %}Offline{% endif %}'
        icon_template: mdi:printer
        friendly_name: HP Printer    

# MOBILE
      device_iconia_tab:
        value_template: '{% if is_state("device_tracker.iconia_tab", "home") %}Online{% else %}Offline{% endif %}'
        icon_template: mdi:tablet
        friendly_name: 'Iconia Tablet' 

      device_galaxy_tab:
        value_template: '{% if is_state("device_tracker.galaxy_tab", "home") or is_state("device_tracker.galaxy_tab_ext", "home") %} Online {% else %} Offline {% endif %}'
        icon_template: mdi:tablet
        friendly_name: 'Galaxy Tablet'

# -- Helen        
      device_nmap_helens_winphone:
        value_template: '{% if is_state("device_tracker.nmap_helens_winphone", "home") %}Online{% else %}Offline{% endif %}'
        icon_template: mdi:cellphone
        friendly_name: Helen's WinPhone

      device_nmap_helens_iphone:
        value_template: '{% if is_state("device_tracker.nmap_helens_iphone", "home") or is_state("device_tracker.nmap_helens_iphone_ext", "home") %} Online {% else %} Offline {% endif %}'
        icon_template: mdi:cellphone-iphone
        friendly_name: Helen's iPhone
        
# -- Roland
      device_nmap_rolands_iphone:
        value_template: '{% if is_state("device_tracker.nmap_rolands_iphone", "home") or is_state("device_tracker.nmap_rolands_iphone_ext", "home") %} Online {% else %} Offline {% endif %}'
        icon_template: mdi:cellphone-iphone
        friendly_name: Roland's iPhone
        
      device_nmap_rolands_nexus:
        value_template: '{% if is_state("device_tracker.nmap_rolands_nexus", "home") %}Online{% else %}Offline{% endif %}'
        icon_template: mdi:cellphone-android
        friendly_name: Roland's Nexus

# HOME AUTOMATION
      device_xiaomi_gateway:
        value_template: '{% if is_state("device_tracker.xiaomi_gateway", "home") %}Online{% else %}Offline{% endif %}'
        icon_template: mdi:image-filter-tilt-shift
        friendly_name: Xiaomi Gateway  

      device_xiaomi_gateway2:
        value_template: '{% if is_state("device_tracker.xiaomi_gateway2", "home") %}Online{% else %}Offline{% endif %}'
        icon_template: mdi:image-filter-tilt-shift
        friendly_name: Xiaomi Gateway  

# SENSOR
      device_efergy_hub:
        value_template: '{% if is_state("device_tracker.efergy_hub", "home") %}Online{% else %}Offline{% endif %}'
        icon_template: mdi:gauge
        friendly_name: Efergy Hub  
 
        
        
automation:
  - alias: Notify for new devices
    trigger:
      platform: event
      event_type: device_tracker_new_device
    action:
      - service: notify.pushover
        data_template:
          message: >
            New device:
            {{trigger.event.data.host_name}}
            ({{trigger.event.data.entity_id}})
          title: New device
          