# all things HARMONY 

# entities:
#
# sensor.harmony_current_activity - what is running now
# input_select.harmony_control    - select what to do next
#
#
#

remote:
  - platform: harmony
    name: HarmonyHub
    username: !secret HARMONY_USER
    password: !secret HARMONY_PWD
    host: !secret HARMONY_IP
    port: 5222
    activity: Watch Plex


sensor:
  platform: template
  sensors:
    harmony_current_activity:
      friendly_name: 'Harmony Current Activity'
      value_template: '{% if states.remote.harmonyhub.state %}{{ states.remote.harmonyhub.attributes.current_activity }}{% endif %}'

      
input_select:
  harmony_control:
    name: Harmony Control
    options:
      - Select Input
      - Watch TV
      - Watch Plex
      - PowerOff
    icon: mdi:settings_remote

automation:

  - alias: Harmony Switch
    hide_entity: True
    trigger:
      platform: state
      entity_id: input_select.harmony_control
      from: 'Select Input'
    action:
      - service: remote.turn_on
        entity_id: remote.harmonyhub
        data_template:
          activity: >
            {% if is_state("input_select.harmony_control", "Watch TV") %}
              23619023
            {% elif is_state("input_select.harmony_control", "Watch Plex") %}
              29111371
            {% elif is_state("input_select.harmony_control", "PowerOff") %}
              -1
            {% endif %}
      - service: input_select.select_option
        entity_id: input_select.harmony_control
        data:
          option: "Select Input"
          
  - alias: Harmony Off
    hide_entity: True
    trigger:
      platform: state
      entity_id: input_select.harmony_control
      to: 'PowerOff'
    action:
      - service: remote.turn_off
        entity_id: remote.harmonyhub
      - service: input_select.select_option
        entity_id: input_select.harmony_control
        data_template:
          option: "Select Input"
  
  
  