# All things XIAOMI

xiaomi:
 gateways:
 # hallway gateway
   - mac: !secret XIAOMI_MAC_1 
     key: !secret XIAOMI_KEY_1  
 # bedroom gateway
   - mac: !secret XIAOMI_MAC_2 
     key: !secret XIAOMI_KEY_2  

homeassistant:
  customize:
    light.gateway_light_286c0785b6f3:
       friendly_name: 'Xiaomi Gateway Light'
    sensor.illumination_286c0785b6f3:
       friendly_name: 'Xiaomi Gateway Light Sensor'       
    binary_sensor.switch_158d00015681b8:
      icon: mdi:checkbox-multiple-blank-circle-outline
      friendly_name: 'Xiaomi Button L'
    binary_sensor.motion_sensor_158d00012dc3de:
      friendly_name: 'Hallway Motion'
    binary_sensor.motion_sensor_158d00014dd669:
      friendly_name: 'Livingroom Motion' 
    binary_sensor.motion_sensor_158d00014dd511:
      friendly_name: 'Kitchen Motion'      
    

    switch.plug_158d00013f9d2a:
      friendly_name: 'Office Light Plug'
    binary_sensor.door_window_sensor_158d00012a885f:
      friendly_name: 'Xiaomi Door Sensor'

    
    binary_sensor.switch_158d0001870e25:
      icon: mdi:checkbox-multiple-blank-circle-outline
      friendly_name: 'Xiaomi Button R'
    switch.plug_158d00013e8964_2:
      friendly_name: 'Rolands Light Plug'

    switch.plug_158d0001288e14:
      friendly_name: 'Helens Light Plug'      
    binary_sensor.switch_158d000186dfe4:
      icon: mdi:checkbox-multiple-blank-circle-outline
      friendly_name: 'Xiaomi Button H'

      
    sensor.illumination_f0b429cfbc12:
       friendly_name: 'Xiaomi Gateway 2 Light Sensor' 
    light.gateway_light_f0b429cfbc12:    
       friendly_name: 'Xiaomi Gateway 2 Light'      
      
# Hallway Temperature and Humidity      
    sensor.temperature_158d0001576d20:
      friendly_name: 'Hallway Temperature'
    sensor.humidity_158d0001576d20:
      friendly_name: 'Hallway Humidity'
    sensor.hallway:
      friendly_name: 'Hallway'
      icon: mdi:oil-temperature    

# Balcony Temperature and Humidity
    sensor.temperature_158d00015763d7:
      friendly_name: 'Balcony Temperature'
    sensor.humidity_158d00015763d7:
      friendly_name: 'Balcony Humidity'
    sensor.balcony:
      friendly_name: 'Balcony'
      icon: mdi:oil-temperature    
      
# Laundry Temperature and Humidity      
    sensor.temperature_158d0001573b30:
      friendly_name: 'Laundry Temperature'
    sensor.humidity_158d0001573b30:
      friendly_name: 'Laundry Humidity'
    sensor.laundry:
      friendly_name: 'Laundry'
      icon: mdi:oil-temperature  

# sensors just for graphs
    sensor.graph_front_door:
      hidden: true    
    sensor.graph_hallway_motion:
      hidden: true

sensor:
  - platform: template
    sensors: 
      hallway:
        value_template: '{{ states("sensor.temperature_158d0001576d20")|int}}C at {{states("sensor.humidity_158d0001576d20")|int}}% Humidity'
      balcony:
        value_template: '{{ states("sensor.temperature_158d00015763d7")|int}}C at {{states("sensor.humidity_158d00015763d7")|int}}% Humidity'
      laundry:
        value_template: '{{ states("sensor.temperature_158d0001573b30")|int}}C at {{states("sensor.humidity_158d0001573b30")|int}}% Humidity'

      front_door:
        friendly_name: Front Door   
        value_template: >-
          {% if states.binary_sensor.door_window_sensor_158d00012a885f.state == 'on' %}
            Open
          {% elif states.binary_sensor.door_window_sensor_158d00012a885f.state == 'off' %}
            Closed
          {% else %}
            n/a
          {% endif %}
          
   
      
      graph_front_door:
        unit_of_measurement: 'graph'      
        value_template: >-
          {% if states.binary_sensor.door_window_sensor_158d00012a885f.state == 'on' %}
            1
          {% elif states.binary_sensor.door_window_sensor_158d00012a885f.state == 'off' %}
            0
          {% else %}
            -1
          {% endif %}

      graph_hallway_motion:
        unit_of_measurement: 'graph'
        value_template: >-
          {% if states.binary_sensor.motion_sensor_158d00012dc3de.state == 'on' %}
            1
          {% elif states.binary_sensor.motion_sensor_158d00012dc3de.state == 'off' %}
            0
          {% else %}
            -1
          {% endif %}
          
          
          
automation:
- alias: Hallway Lights by motion at night ON
  initial_state: 'on'
 # hidden: True
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d00012dc3de
      to: 'on'
  action:
    service: homeassistant.turn_on
    data:
      entity_id: light.gateway_light_286c0785b6f3
      rgb_color: [25,0,150]
      brightness: 75

- alias: Hallway Lights by motion at night OFF
  initial_state: 'on'
#  hidden: True
#  condition:
#    - condition: state
#      entity_id: sun.sun
#      state: 'below_horizon'
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d00012dc3de
      to: 'off'
      for:
        minutes: 0
        seconds: 30
  action:
    service: homeassistant.turn_off
    data:
      entity_id: light.gateway_light_286c0785b6f3


# Bedroom Desk/Office Lamp
# -----------------------     
- alias: Toggle Light Plug
  initial_state: 'on'
 # hidden: True
  trigger:
    platform: event
    event_type: click
    event_data:
      # Switch L
      entity_id: binary_sensor.switch_158d00015681b8
      click_type: single
  action:
    service: homeassistant.toggle
    data:
      entity_id: switch.plug_158d00013f9d2a

      
# Bedside Table Lamps
# -----------------------

# Roland's Light
- alias: Toggle Rolands Light
  initial_state: 'on'
  trigger:
    platform: event
    event_type: click
    event_data:
      # Switch R
      entity_id: binary_sensor.switch_158d0001870e25
      click_type: single
  action:
    service: homeassistant.toggle
    data:
      entity_id: switch.plug_158d00013e8964_2


# Helen's Light      
- alias: Toggle Helens Light
  initial_state: 'on'
  trigger:
    platform: event
    event_type: click
    event_data:
      # Switch H
      entity_id: binary_sensor.switch_158d000186dfe4
      click_type: single
  action:
    service: homeassistant.toggle
    data:
      entity_id: switch.plug_158d0001288e14   

      
- alias: All Bedroom Lights OFF
  initial_state: 'on'
  trigger:
    # Switch L
    - platform: event
      event_type: click
      event_data:
        entity_id: binary_sensor.switch_158d00015681b8
        click_type: double
    # Switch R    
    - platform: event
      event_type: click
      event_data:
        entity_id: binary_sensor.switch_158d0001870e25
        click_type: double
    # Switch H
    - platform: event
      event_type: click
      event_data:
        entity_id: binary_sensor.switch_158d000186dfe4
        click_type: double        
  action:
    service: homeassistant.turn_off
    entity_id: group.BedroomLights

      