# All things XIAOMI

xiaomi_aqara:
 gateways:
 # hallway gateway
   - mac: !secret XIAOMI_MAC_1
     key: !secret XIAOMI_KEY_1
 # bedroom gateway
   - mac: !secret XIAOMI_MAC_2
     key: !secret XIAOMI_KEY_2

     
light:
  - platform: yeelight
    devices:
      192.168.2.80:
        #34:CE:00:87:F7:93
        name: Laundry Light
        transition: 1000     
      192.168.2.81: 
        name: Wardrobe Light
        transition: 1000
      192.168.2.82: 
        name: Bathroom Light
        transition: 1000     
      192.168.2.83:
        name: Bedroom Light
        transition: 1000          
      192.168.2.84:
        name: Ensuite Light
        transition: 1000          
      192.168.2.85:
        name: Felix Light
        transition: 1000       
        
homeassistant:
  customize:
  
  # Friendly names are now assiged in entity_registry.yaml
  # an entity id is also assigend there. 
  
  
    binary_sensor.switch_button_l:
      icon: mdi:checkbox-multiple-blank-circle-outline

    binary_sensor.switch_button_r:
      icon: mdi:checkbox-multiple-blank-circle-outline

    binary_sensor.switch_button_h:
      icon: mdi:checkbox-multiple-blank-circle-outline

    sensor.hallway:
      icon: mdi:oil-temperature

# sensors just for graphs
    sensor.graph_front_door:
      hidden: true
    sensor.graph_hallway_motion:
      hidden: true

sensor:
  - platform: template
    sensors:
      hallway:
        value_template: '{{ states("sensor.temperature_hallway")|int}}C at {{states("sensor.humidity_hallway")|int}}% Humidity'
      balcony:
        value_template: '{{ states("sensor.temperature_balcony")|int}}C at {{states("sensor.humidity_balcony")|int}}% Humidity'
      laundry:
        value_template: '{{ states("sensor.temperature_ensuite")|int}}C at {{states("sensor.humidity_ensuite")|int}}% Humidity'
      humidity_delta:
        value_template: '{{ states("sensor.humidity_ensuite")|int - states("sensor.humidity_hallway")|int}}'
        unit_of_measurement: '%'
        friendly_name: Humidity compared to Hallway
        
      front_door:
        friendly_name: Front Door
        value_template: >-
          {% if states.binary_sensor.door_appartment_door.state == 'on' %}
            Open
          {% elif states.binary_sensor.door_appartment_door.state == 'off' %}
            Closed
          {% else %}
            n/a
          {% endif %}



      graph_front_door:
        unit_of_measurement: 'graph'
        value_template: >-
          {% if states.binary_sensor.door_appartment_door.state == 'on' %}
            1
          {% elif states.binary_sensor.door_appartment_door.state == 'off' %}
            0
          {% else %}
            -1
          {% endif %}

      graph_hallway_motion:
        unit_of_measurement: 'graph'
        value_template: >-
          {% if states.binary_sensor.motion_hallway.state == 'on' %}
            1
          {% elif states.binary_sensor.motion_hallway.state == 'off' %}
            0
          {% else %}
            -1
          {% endif %}
