# All things XIAOMI

xiaomi_aqara:
 gateways:
 # hallway gateway
   - mac: !secret XIAOMI_MAC_1
     key: !secret XIAOMI_KEY_1
 # bedroom gateway
   - mac: !secret XIAOMI_MAC_2
     key: !secret XIAOMI_KEY_2

     
light:
  - platform: yeelight
    devices:
      192.168.2.80:
        #34:CE:00:87:F7:93
        name: Laundry Light
        transition: 1000     
      192.168.2.81: 
        name: Wardrobe Light
        transition: 1000
      192.168.2.82: 
        name: Bathroom Light
        transition: 1000     
      192.168.2.83:
        name: Bedroom Light
        transition: 1000          
      192.168.2.84:
        name: Ensuite Light
        transition: 1000          
        
homeassistant:
  customize:
# ------------------------
# GATEWAYS



# ------------------------
#   Gateway - Bedroom
# ------------------------
    light.gateway_light_f0b429cfbc12:
       friendly_name: 'Xiaomi Gateway 2 Light'


# ------------------------
# DEVICES
# ------------------------
#   Devices - Bedroom
# ------------------------

    # Ceiling Light
    light.bedroom_light:
      friendly_name: 'Bedroom Light'
      google_assistant: true
      google_assistant_name: 'Ceiling Light'      

    # Wardrobe Light
    light.wardrobe_light:
      friendly_name: 'Wardrobe Light'
      google_assistant: true
      google_assistant_name: 'Wardrobe Light'           

        
    # Ensuite Light
    light.ensuite_light:
      friendly_name: 'Ensuite Light'
      google_assistant: true
      google_assistant_name: 'Ensuite Light'   
    # Ensuite Motion

      
    # Desk Light
    binary_sensor.switch_button_l:
      icon: mdi:checkbox-multiple-blank-circle-outline


    switch.plug_desk_light:
      friendly_name: 'Desk Light Plug'
      google_assistant: true
      google_assistant_name: 'Desk Light'

    # Roland's Light
    binary_sensor.switch_button_r:
      icon: mdi:checkbox-multiple-blank-circle-outline

    switch.plug_rolands_light:
      google_assistant_name: 'Roland''s Light'
      google_assistant: true

    # Helen's Light
    binary_sensor.switch_button_h:
      icon: mdi:checkbox-multiple-blank-circle-outline

    switch.plug_158d0001288e14:
      friendly_name: 'Helen''s Light Plug'
      google_assistant: true
      google_assistant_name: 'Helen''s Light'
      
      
    

# ------------------------
#   Devices - Hallway
# ------------------------
    binary_sensor.door_appartment_door:
      friendly_name: 'Xiaomi Door Sensor'

    sensor.hallway:
      friendly_name: 'Hallway'
      icon: mdi:oil-temperature


# ------------------------
#   Devices - Livingroom
# ------------------------

    switch.plug_xmas_tree:
      friendly_name: 'XMas Tree Plug'    
      google_assistant: true
      google_assistant_name: 'Christmas Tree'
      google_assistant_type: switch




# ------------------------
#   Devices - Balcony
# ------------------------
    # Balcony Temperature and Humidity

    sensor.humidity_balcony:
      friendly_name: 'Balcony Humidity'
    sensor.balcony:
      friendly_name: 'Balcony'
      icon: mdi:oil-temperature

# ------------------------
#   Devices - Laundry
# ------------------------
   # Laundry Temperature and Humidity


    sensor.laundry:
      friendly_name: 'Laundry'
      icon: mdi:oil-temperature
    binary_sensor.water_leak_sensor_158d0001d593cc:
      friendly_name: 'Water Leak Sensor'
    light.laundry_light:
      friendly_name: 'Laundry Light'
      google_assistant: true
      google_assistant_name: 'Laundry Light'    

# ------------------------
#   Devices - Bathroom
# ------------------------
    # Bathroom Light
    light.bathroom_light:
      friendly_name: 'Bathroom Light'
      google_assistant: true
      google_assistant_name: 'Bathroom Light'   


# sensors just for graphs
    sensor.graph_front_door:
      hidden: true
    sensor.graph_hallway_motion:
      hidden: true

sensor:
  - platform: template
    sensors:
      hallway:
        value_template: '{{ states("sensor.temperature_hallway")|int}}C at {{states("sensor.humidity_hallway")|int}}% Humidity'
      balcony:
        value_template: '{{ states("sensor.temperature_balcony")|int}}C at {{states("sensor.humidity_balcony")|int}}% Humidity'
      laundry:
        value_template: '{{ states("sensor.temperature_ensuite")|int}}C at {{states("sensor.humidity_ensuite")|int}}% Humidity'
      humidity_delta:
        value_template: '{{ states("sensor.humidity_ensuite")|int - states("sensor.humidity_hallway")|int}}'
        unit_of_measurement: '%'
        friendly_name: Humidity compared to Hallway
        
      front_door:
        friendly_name: Front Door
        value_template: >-
          {% if states.binary_sensor.door_appartment_door.state == 'on' %}
            Open
          {% elif states.binary_sensor.door_appartment_door.state == 'off' %}
            Closed
          {% else %}
            n/a
          {% endif %}



      graph_front_door:
        unit_of_measurement: 'graph'
        value_template: >-
          {% if states.binary_sensor.door_appartment_door.state == 'on' %}
            1
          {% elif states.binary_sensor.door_appartment_door.state == 'off' %}
            0
          {% else %}
            -1
          {% endif %}

      graph_hallway_motion:
        unit_of_measurement: 'graph'
        value_template: >-
          {% if states.binary_sensor.motion_hallway.state == 'on' %}
            1
          {% elif states.binary_sensor.motion_hallway.state == 'off' %}
            0
          {% else %}
            -1
          {% endif %}



automation:
- alias: Hallway Lights by motion at night ON
  initial_state: 'on'
 # hidden: True
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_hallway
      to: 'on'
  action:
    service: homeassistant.turn_on
    data:
      entity_id: light.gateway_light_hallway
      rgb_color: [25,0,150]
      brightness: 75

- alias: Hallway Lights by motion at night OFF
  initial_state: 'on'
#  hidden: True
#  condition:
#    - condition: state
#      entity_id: sun.sun
#      state: 'below_horizon'
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_hallway
      to: 'off'
      for:
        minutes: 0
        seconds: 30
  action:
    service: homeassistant.turn_off
    data:
      entity_id: light.gateway_light_hallway

      
      
      
#  Wardrobe Light by Motion
# =================================================
- alias: Wardrobe Light by motion ON
  initial_state: 'on'
 # hidden: True
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_wardrobe
      to: 'on'
  action:
    service: homeassistant.turn_on
    data:
      entity_id: light.wardrobe_light
      #rgb_color: [25,0,150]
      brightness: 255

- alias: Wardrobe Light by motion OFF
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_wardrobe
      to: 'off'
      for:
        minutes: 0
        seconds: 30
    - platform: state
      entity_id: light.wardrobe_light
      from: 'unavailable'
      to: 'on'
      for:
        minutes: 0
        seconds: 10
  action:
    service: homeassistant.turn_off
    data:
      entity_id: light.wardrobe_light
      
#  Ensuite Light by Motion
# =================================================
- alias: Ensuite Light by motion ON
  initial_state: 'on'
 # hidden: True
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_ensuite
      to: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: light.ensuite_light
    data_template: 
      brightness: >
        {% if   states.sensor.time_of_day.state == "night" %} 80
        {% else %} 255
        {% endif %}
      color_name: >
        {% if   states.sensor.time_of_day.state == "night"  %} blue
        {% else %} white
        {% endif %}
        
- alias: Ensuite Light by motion OFF
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_ensuite
      to: 'off'
      for:
        minutes: 0
        seconds: 30
    - platform: state
      entity_id: light.ensuite_light
      from: 'unavailable'
      to: 'on'
      for:
        minutes: 0
        seconds: 10
  action:
    service: homeassistant.turn_off
    data:
      entity_id: light.ensuite_light
      
#  Ensuite Fan by Motion
# =================================================
# switch on fan after motion for 1 minute.
# no fan at night! too noisy

- alias: Ensuite Fan by motion ON
  initial_state: 'on'
 # hidden: True
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_ensuite
      to: 'on'
      for:
        minutes: 1
        seconds: 0
  condition:
    condition: template
    value_template: '{{ states.sensor.time_of_day.state != "night" }}'          
  action:
    service: homeassistant.turn_on
    entity_id: switch.ensuite_fan
        
- alias: Ensuite Fan by motion OFF
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_ensuite
      to: 'off'
      for:
        minutes: 5
        seconds: 30
  action:
    service: homeassistant.turn_off
    data:
      entity_id: switch.ensuite_fan

      
#  BATHROOM Light by Motion 
# =================================================
- alias: Bathroom Light by motion ON
  initial_state: 'on'
 # hidden: True
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_bathroom
      to: 'on'
  condition:
    condition: template
    value_template: '{{ states.sensor.light_of_day.state != "light" }}'    
    # only switch on the light if it is not LIGHT outside now
  action:
    service: homeassistant.turn_on
    data:
      entity_id: light.bathroom_light
      #rgb_color: [25,0,150]
      brightness: 255

- alias: Wardrobe Light by motion OFF
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_bathroom
      to: 'off'
      for:
        minutes: 3
        seconds: 30
  action:
    service: homeassistant.turn_off
    data:
      entity_id: light.bathroom_light
      

      

# Bedroom Desk/Office Lamp
# -----------------------
- alias: Toggle Light Plug
  initial_state: 'on'
 # hidden: True
  trigger:
    platform: event
    event_type: click
    event_data:
      # Switch L
      entity_id: binary_sensor.switch_button_l
      click_type: single
  action:
    service: homeassistant.toggle
    data:
      entity_id: switch.plug_desk_light


# Bedside Table Lamps
# -----------------------

# Roland's Light
- alias: Toggle Rolands Light
  initial_state: 'on'
  trigger:
    platform: event
    event_type: click
    event_data:
      # Switch R
      entity_id: binary_sensor.switch_button_r
      click_type: single
  action:
    - service: homeassistant.toggle
      data:
        entity_id: switch.plug_rolands_light




# Helen's Light
- alias: Toggle Helens Light
  initial_state: 'on'
  trigger:
    platform: event
    event_type: click
    event_data:
      # Switch H
      entity_id: binary_sensor.switch_button_h
      click_type: single
  action:
    service: homeassistant.toggle
    data:
      entity_id: switch.plug_158d0001288e14


- alias: All Bedroom Lights OFF
  initial_state: 'on'
  trigger:
    # Switch L
    - platform: event
      event_type: click
      event_data:
        entity_id: binary_sensor.switch_button_l
        click_type: double
    # Switch R
    - platform: event
      event_type: click
      event_data:
        entity_id: binary_sensor.switch_button_r
        click_type: double
    # Switch H
    - platform: event
      event_type: click
      event_data:
        entity_id: binary_sensor.switch_button_h
        click_type: double
  action:
    service: homeassistant.turn_off
    entity_id: group.BedroomLights

- alias: Bedroom Ceiling Light toggle
  initial_state: 'on'
  trigger:
    # Switch L
    - platform: event
      event_type: click
      event_data:
        entity_id: binary_sensor.switch_button_l
        click_type: long_click_press
    # Switch R
    - platform: event
      event_type: click
      event_data:
        entity_id: binary_sensor.switch_button_r
        click_type: long_click_press
    # Switch H
    - platform: event
      event_type: click
      event_data:
        entity_id: binary_sensor.switch_button_h
        click_type: long_click_press
  action:
    service: homeassistant.toggle
    entity_id: light.bedroom_light
    
    
    
    
#  Laundry Light by Motion
# =================================================
- alias: Laundry Light by motion ON
  initial_state: 'on'
 # hidden: True
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_laundry
      to: 'on'
  action:
    service: homeassistant.turn_on
    data:
      entity_id: light.laundry_light
      #rgb_color: [25,0,150]
      brightness: 255

- alias: Laundry Light by motion OFF
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_laundry
      to: 'off'
      for:
        minutes: 3
  action:
    service: homeassistant.turn_off
    data:
      entity_id: light.laundry_light    