# All things Wall Panel
      
      
device_tracker:
  - platform: mqtt_json
    devices:
      Nexus5Z: zanzito/Nexus5/location


sensor:
  - platform: mqtt
    name: "Nexus5Z Battery"
    state_topic: "zanzito/Nexus5/battery_level"
    qos: 0
    unit_of_measurement: "%"

binary_sensor:
  - platform: mqtt
    name: "Zanzito status"
    state_topic: "zanzito/Nexus5/status"
    payload_on: "1"
    payload_off: "0"
    device_class: connectivity      
      
