---
# Pihole 5
# enable disable group to block/unblock all domains for all clients in the group
# inspiration from here: https://discourse.pi-hole.net/t/activate-group-with-cron/32660/8

platform: command_line
switches:
  pihole_xenia_novideo:
    command_on: ssh -oStrictHostKeyChecking=no root@192.168.2.130 'docker exec pihole5 bash /etc/pihole/setGroupStatus.sh Xenia-NoVideos enable'
    command_off: ssh -oStrictHostKeyChecking=no root@192.168.2.130 'docker exec pihole5 bash /etc/pihole/setGroupStatus.sh Xenia-NoVideos disable'
    command_state: ssh -oStrictHostKeyChecking=no root@192.168.2.130 'docker exec pihole5 bash /etc/pihole/setGroupStatus.sh Xenia-NoVideos status'
    value_template: '{{ value == "1" }}'
    friendly_name: Xenia Block Video
