---
# Automation running in the Master Bedroom
#
# All OFF from any of the buttons

alias: All Bedroom Lights OFF
initial_state: 'on'
trigger:
  # Button L
  - platform: state
    entity_id: sensor.button_l_click
    to: 'double'
  # Switch R
  - platform: state
    entity_id: sensor.button_r_click
    to: 'double'
  # Switch H
  - platform: state
    entity_id: sensor.button_h_click
    to: 'double'
  # Button C - Ceiling
  - platform: state
    entity_id: sensor.button_c_click
    to: 'double'
action:
  service: homeassistant.turn_off
  entity_id: group.BedroomLights
