---
# Automation running in the Master Bedroom
#
# Ceiling light toggle
# this can be done from any of the 3 buttons
# using a long press

alias: Bedroom Ceiling Light toggle
initial_state: 'on'
trigger:
  # Switch L
  - platform: state
    entity_id: sensor.button_l_action
    to: 'hold'
  # Switch R
  - platform: state
    entity_id: sensor.button_r_action
    to: 'hold'
  # Switch H
  - platform: state
    entity_id: sensor.button_h_action
    to: 'hold'
  # Switch C
  - platform: state
    entity_id: sensor.button_c_action
    to: 'single'

action:
  service: homeassistant.toggle
  entity_id: light.bedroom_light
