---
# Automation running in the Master Bedroom
#
# Bedroom Desk/Office Lamp toggle

alias: Toggle Light Plug
initial_state: 'on'
trigger:
  platform: state
  entity_id: sensor.button_l_click
  to: 'single'
action:
  service: homeassistant.toggle
  data:
    entity_id: switch.plug_l_switch
