---
# Automation running in the Master Bedroom
#
# Bedside Table Lamp Helen Toggle

alias: Toggle Helens Light
initial_state: 'on'
trigger:
  - platform: state
    entity_id: sensor.button_h_action
    to: 'single'
action:
  service: homeassistant.toggle
  data:
    entity_id: switch.helens_light
