---
# Automation running in the Master Bedroom
#
# Bedside Table Lamp Roland Toggle

alias: Toggle Rolands Light
initial_state: 'on'
trigger:
  platform: event
  event_type: xiaomi_aqara.click
  event_data:
    entity_id: binary_sensor.switch_button_r
    click_type: single
action:
  service: homeassistant.toggle
  data:
    entity_id: switch.plug_rolands_light
