---
# --------------------------------------
# Floorplan
# --------------------------------------
title: Floorplan
id: floorplan
cards:
  - type: picture-elements
    image: /local/floorplanX.png

    elements:
      # ---- Master Bedroom
      - type: state-icon
        entity: light.bedroom_light
        style:
          top: 78%
          left: 37%
      - type: state-icon
        entity: light.bathroom_light
        style:
          top: 17%
          left: 43%
      - type: state-icon
        entity: switch.plug_rolands_light
        style:
          top: 86%
          left: 48%
      - type: state-icon
        entity: switch.plug_helens_light
        style:
          top: 72%
          left: 48%
      - type: state-icon
        entity: switch.plug_desk_light
        style:
          top: 88%
          left: 30%

      # ---- Ensuite
      - type: state-icon
        entity: light.ensuite_light
        style:
          top: 52%
          left: 28%
      - type: state-icon
        entity: binary_sensor.motion_ensuite
        style:
          top: 52.5%
          left: 35%

      # ---- Wardrobe
      - type: state-icon
        entity: light.wardrobe_light
        style:
          top: 55%
          left: 44%

      # ---- Laundry
      - type: state-icon
        entity: binary_sensor.motion_laundry
        style:
          top: 18%
          left: 63%
      - type: state-icon
        entity: light.laundry_light
        style:
          top: 25%
          left: 59%
