---
path: rooms
title: Rooms
icon: mdi:sofa

cards:
  - type: horizontal-stack
    cards:
      - type: vertical-stack
        cards:
          - type: vertical-stack
            title: Master Bedroom
            cards:
              - type: custom:auto-entities
                card:
                  type: entities
                  title: Bedroom
                  show_header_toggle: false
                filter:
                  include:
                    - group: group.roomsbedroom
              - type: entities
                entities:
                  - media_player.master_bedroom_speaker
              - type: custom:auto-entities
                card:
                  type: entities
                  title: Ensuite
                  show_header_toggle: false
                filter:
                  include:
                    - group: group.roomsensuite

# 2nd column
  - type: horizontal-stack
    cards:
      - type: vertical-stack
        cards:
          - type: custom:auto-entities
            card:
              type: entities
              title: Living Room
              show_header_toggle: false
            filter:
              include:
                - group: group.roomslivingroom
          - type: custom:auto-entities
            card:
              type: entities
              title: Bathroom
              show_header_toggle: false
            filter:
              include:
                - group: group.roomsbathroom

          - type: custom:auto-entities
            card:
              type: entities
              title: Laundry
              show_header_toggle: false
            filter:
              include:
                - group: group.roomslaundry

          - type: custom:auto-entities
            card:
              type: entities
              title: Hallway
              show_header_toggle: false
            filter:
              include:
                - group: group.roomshallway


# 3rd column
  - type: horizontal-stack
    cards:
      - type: vertical-stack
        cards:
          - type: vertical-stack
            title: Felix's Room
            cards:
              - type: custom:auto-entities
                card:
                  type: entities
                  title: Devices
                  show_header_toggle: false
                filter:
                  include:
                    - group: group.roomsfelix
              - type: entities
                entities:
                  - media_player.felix_s_speaker
          - type: vertical-stack
            title: Xenia's Room
            cards:
              - type: custom:auto-entities
                card:
                  type: entities
                  title: Devices
                  show_header_toggle: false
                filter:
                  include:
                    - group: group.roomsxenia
              - type: entities
                entities:
                  - media_player.xenia_s_speaker
