---
path: stuff
title: stuff
#icon: mdi:sofa

cards:
  - type: horizontal-stack
    cards:  
    - type: vertical-stack
      cards:
        - type: custom:auto-entities
          card:
            type: entities
            title: Automations
            show_header_toggle: false
          filter:
            include:
              - domain: automation    

#2nd column                   
  - type: horizontal-stack
    cards:  
    - type: vertical-stack
      cards:
        - type: custom:auto-entities
          card:
            type: entities
            title: Lights
            show_header_toggle: false
          filter:
            include:
              - domain: light   


# 3rd column
  - type: horizontal-stack
    cards:  
    - type: vertical-stack
      cards:
        - type: custom:auto-entities
          card:
            type: entities
            title: devices
            show_header_toggle: false
          filter:
            include:
              - domain: sensor
                entity_id: "sensor.device*"