---
# Automation in Felix's room to toggle the light via button press

alias: Toggle Felix Light
initial_state: 'on'
trigger:
  - platform: state
    entity_id: sensor.button_f_action
    to: 'single'
action:
  service: homeassistant.toggle
  data:
    entity_id: light.felix_light
