---
# Automation running in the laundry
#
#
#  Laundry Light by Motion

alias: Laundry Light by motion ON
initial_state: 'on'
trigger:
  - platform: state
    entity_id: binary_sensor.laundry_motion
    to: 'on'
action:
  service: homeassistant.turn_on
  data:
    entity_id: light.laundry_light
    brightness: 255
