---
# Group for Felix's Room
#

RoomsFelix:
  name: Felix's Room
  view: false
  entities:
    - light.felix_light
    - binary_sensor.switch_button_f
    - sensor.device_google_home_felix
