---
# Group defined as VIEW
#

Devices_MediaPlayer:
  name: Media Player
  view: false
  entities:
    - sensor.device_chromecast
    - sensor.device_audiocast
    - sensor.device_fetch
    - sensor.device_roku
    - sensor.device_sonos_playbar
