---
# Group defined as VIEW
#

Environment:
  view: false
  entities:
    - sensor.humidity_hallway
    - sensor.temperature_hallway
    - sensor.temperature_balcony
    - sensor.humidity_balcony
    - sun.sun    
