---
# Group defined as VIEW
#

Xiaomi2:
  name: Gateway 2
  view: false
  entities:
    - sensor.device_xiaomi_gateway2
    - light.gateway_light_gateway2
    - sensor.illumination_gateway2
    # Rolands Light
    - sensor.button_r_click
    - switch.plug_r
    # Helens Light
    - binary_sensor.switch_button_h
    - switch.plug_helens_light
    # bedroom
    - binary_sensor.motion_wardrobe
    - light.bedroom_light
    - light.wardrobe_light
