---
# Group defined as VIEW
#

Devices_Computer:
  name: Computer
  view: false
  entities:
    - sensor.device_blue_laptop
    - sensor.device_obelix
    - sensor.device_blue_laptop
    - sensor.device_purple_laptop
    - sensor.device_hp_tablet
