---
# Group defined as VIEW
#

Devices_Mobiles:
  name: Mobiles
  view: false
  entities:
    - sensor.device_nmap_helens_iphone
    - sensor.device_nmap_helens_workphone
    - sensor.device_nmap_rolands_iphone
    - sensor.device_nmap_rolands_nokia
    - sensor.rolands_work_phone_battery_state
    - sensor.rolands_work_phone_battery_level
    - sensor.device_nmap_rolands_nexus
    - sensor.zan_nexus_battery
    - sensor.device_galaxy_tab
