---
# Group defined as VIEW
#

Devices_Network:
  name: Network
  view: false
  entities:
    - sensor.device_modem_router
    # - sensor.device_repeater
    # - sensor.device_access_point
    - sensor.device_gate_pi
    - sensor.device_hp_printer
