---
# Group to hold the custom component trackers
#

trackers:
  view: false
  entities:
    - sensor.custom_component_tracker
    - sensor.custom_python_script_tracker
    - sensor.custom_card_tracker
