---
# Group defined as VIEW
#

RoomsHallway:
  name: Hallway
  view: false
  entities:
    - sensor.device_xiaomi_gateway
    - light.gateway_light_hallway
    - sensor.illumination_hallway
    - sensor.humidity_hallway
    - sensor.temperature_hallway
