---
# Humidity Delta
# Compares the humidity between hallway and ensuite
# used to run the exhaust fan in the ensuite
#

platform: template
sensors:
  humidity_delta:
    value_template: '{{ states("sensor.ensuite_envirosensor_humidity")|int(0) -
                        states("sensor.hallway_humidity")|int(0)}}'
    unit_of_measurement: '%'
    friendly_name: Humidity compared to Hallway
