---
# Automations running in the bathroom
#  BATHROOM Light by Motion OFF

alias: Bathroom Light by motion OFF
initial_state: 'on'
trigger:
  - platform: state
    entity_id: binary_sensor.bathroom_motion
    to: 'off'
    for:
      minutes: 3
      seconds: 30
action:
  service: homeassistant.turn_off
  data:
    entity_id: light.bathroom_light
