# Automation running in the ensuite
# switch off the light on no motion
#
        
alias: Ensuite Light by motion OFF
initial_state: 'on'
trigger:
  - platform: state
    entity_id: binary_sensor.motion_ensuite
    to: 'off'
    for:
      minutes: 0
      seconds: 30
  - platform: state
    entity_id: light.ensuite_light
    from: 'unavailable'
    to: 'on'
    for:
      minutes: 0
      seconds: 10
action:
  service: homeassistant.turn_off
  data:
    entity_id: light.ensuite_light