# Automation running in the ensuite
#
# switch fan off after 5 minutes of running    
# if there is still motion it will start again
# if it is still humid it will start as well
alias: Ensuite Fan OFF after 5:30 min
initial_state: 'on'
trigger:
  - platform: state
    entity_id: switch.ensuite_fan
    from: 'off'
    to: 'on'
    for:
      minutes: 5
      seconds: 30
action:
  service: homeassistant.turn_off
  data:
    entity_id: switch.ensuite_fan