---
# custom component Composite Device Tracker
#
# https://github.com/pnbruckner/homeassistant-config/blob/master/docs/composite.md
#

platform: composite
name: Roland
entity_id:
  - device_tracker.nmap_rolands_iphone
  - device_traker.mobile_nokia6
  - device_tracker.nmap_rolands_nokia
