---
# Device Trackers

# the netowrk is split into segments, and separate trackers cover them
#
# DHCP: 10 - 50
# Lights 80 - 99
# Google Homes / casts: 100 - 129
# Servers / Media  / Xiaomi : 130 - 150

# servers (Unraid, Roku, RasPlex)
platform: nmap_tracker
track_new_devices: true
hosts: --top-port 1 -Pn 192.168.2.100-150
interval_seconds: 300
home_interval: 60
