# --------------------------------------------------
# Automations running in the hallway
# --------------------------------------------------

- alias: Hallway Lights by motion at night ON
  initial_state: 'on'
 # hidden: True
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_hallway
      to: 'on'
  action:
    service: homeassistant.turn_on
    data:
      entity_id: light.gateway_light_hallway
      rgb_color: [25,0,150]
      brightness: 75

- alias: Hallway Lights by motion at night OFF
  initial_state: 'on'
#  hidden: True
#  condition:
#    - condition: state
#      entity_id: sun.sun
#      state: 'below_horizon'
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_hallway
      to: 'off'
      for:
        minutes: 0
        seconds: 30
  action:
    service: homeassistant.turn_off
    data:
      entity_id: light.gateway_light_hallway