# --------------------------------------------------
# Automations running in the Master Bedroom
# --------------------------------------------------

# Bedroom Desk/Office Lamp
# -----------------------
- alias: Toggle Light Plug
  initial_state: 'on'
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_button_l
      click_type: single
  action:
    service: homeassistant.toggle
    data:
      entity_id: switch.plug_desk_light


# Bedside Table Lamps
# -----------------------

- alias: Toggle Rolands Light
  initial_state: 'on'
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_button_r
      click_type: single
  action:
    - service: homeassistant.toggle
      data:
        entity_id: switch.plug_rolands_light

# Helen's Light
- alias: Toggle Helens Light
  initial_state: 'on'
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_button_h
      click_type: single
  action:
    service: homeassistant.toggle
    data:
      entity_id: switch.plug_helens_light

      
# Ceiling light from any of the 3 buttons
- alias: Bedroom Ceiling Light toggle
  initial_state: 'on'
  trigger:
    # Switch L
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_button_l
        click_type: long_click_press
    # Switch R
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_button_r
        click_type: long_click_press
    # Switch H
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_button_h
        click_type: long_click_press
  action:
    service: homeassistant.toggle
    entity_id: light.bedroom_light
      
# All OFF from any of the buttons
- alias: All Bedroom Lights OFF
  initial_state: 'on'
  trigger:
    # Switch L
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_button_l
        click_type: double
    # Switch R
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_button_r
        click_type: double
    # Switch H
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_button_h
        click_type: double
  action:
    service: homeassistant.turn_off
    entity_id: group.BedroomLights


    
    
    
    
  